-   id: tlv-set-git-vars
    name: tlv-set-git-vars
    description: 'Simple hook to set GIT environment variables'
    entry: tlv-set-git-vars
    language: python
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
