# .pre-commit-config.yaml
repos:
-   repo: https://github.com/mleeman/pre-commit-hooks
    rev: v0.0.0
    hooks:
    -   id: tlv-set-git-vars
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: forbid-submodules
    -   id: mixed-line-ending
    -   id: pretty-format-json
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
