-   id: tlv-set-git-vars
    name: tlv-set-git-vars
    description: 'Simple hook to set GIT environment variables'
    entry: tlv-set-git-vars
    language: python
    files: ^\.git/hooks/pre-commit$
-   id: tlv-deb-copyright-year
    name: tlv-deb-copyright-year
    description: 'Simple to test if the d/copyright is set to the current year'
    entry: tlv-deb-copyright-year
    language: python
    files: ^debian/copyright$
-   id: tlv-deb-standards-version
    name: tlv-deb-standards-version
    description: 'Simple to test if the d/standards-version is set to the current version'
    entry: tlv-deb-standards-version
    language: python
    files: ^debian/control$
-   id: tlv-deb-run-lrc
    name: tlv-deb-run-lrc
    description: 'Run lincensecheck (lrc) on the debian package'
    entry: tlv-deb-run-lrc
    language: python
    files: .*
-   id: tlv-deb-version-fixer
    name: tlv-deb-version-fixer
    description: 'Simple Televic Rail version consistency check'
    entry: tlv-deb-version-fixer
    language: python
    files: ^debian/changelog$
